# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3ed01bbbbfc4bb95441991957480c29b5f383e3fcc1d10091dc61997a8b96079c6c2b1336d20e89539d3e03b9e2efdf4e7a2d5173ded1cc7cca4788b33fa702

test:
  secret_key_base: 8d0d63f040be49fca58d0b434c120a9ed4e09651021c54a5e8efa13c5780ce34b6c549f4d39cc4b476c7fa3353ee5f684574349fe52e509b6e50d6216dd039ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
